### ISSUE TITLE
Performance/benchmarks?

### ISSUE THREAD

**Issue by Kiura** [fate-lovely/fasthttp-chi#2]
Are there any benchmarks or comparisons with other libraries? Does this lib do any allocations?

**Comment by illotum** [comment]
This library allocates strings for parsed path params, though amortized with object pool. This library should be as fast as https://github.com/go-chi/chi#benchmarks.

My understanding is, further in lib's development it will be possible to store only slices or even just indices to the URL, but it might take a while.

**Comment by Kiura** [comment]
I see, thx for clarifications. I was trying to compare this one to fasthttprouter, for this one has better API, whereas the other one is fast.

**Comment by cj1128** [comment]
thanks illotum's explanation, this library is a direct port from chi, I didn't change the inner implementation, so the performance should be the same as chi. I will add some benchmarks if I have time. Currently, I am digging fasthttp's source cause it has some bugs and the maintenance is a problem.
